export const C = {
  green:        '#00A651',
  greenDark:    '#007A3C',
  greenLight:   '#E8F8EE',
  greenMid:     '#80CFA8',
  bg:           '#F8FAFC',
  card:         '#FFFFFF',
  text:         '#0F172A',
  text2:        '#475569',
  text3:        '#94A3B8',
  border:       '#E2E8F0',
  red:          '#DC2626',
  redLight:     '#FEF2F2',
  redBorder:    '#FECACA',
  yellow:       '#D97706',
  yellowLight:  '#FFFBEB',
  yellowBorder: '#FDE68A',
  white:        '#FFFFFF',
}
